<a href="https://colab.research.google.com/github/Dipam-Bhuyan/Dipam-Bhuyan/blob/main/Day3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
x1=np.array([[3, 7, 5, 5],
      [0, 1, 5, 9],
      [3, 0, 5, 0],
      [1, 2, 3, 4]])
print(x1)
print(x1.shape)
uniqueValues, indicesList, frequency = np.unique(x1, return_index=True,return_counts=True)
UniqueList=list(zip(uniqueValues, frequency))
print(UniqueList)

[[3 7 5 5]
 [0 1 5 9]
 [3 0 5 0]
 [1 2 3 4]]
(4, 4)
[(0, 3), (1, 2), (2, 1), (3, 3), (4, 1), (5, 4), (7, 1), (9, 1)]


In [ ]:
import numpy as np
x1=np.array([[3, 7, 5, 5],
      [10, 1, 5, 9],
      [3, 10, 5, 10],
      [1, 2, 3, 4]])
print(x1)
print("\n")
x2=np.unique(x1)
print(x2)
x3=x2.tolist().count(0)
if x3 > 0:
  print("Zero is in the array")
else:
  print("Zero is not in the array")

[[ 3  7  5  5]
 [10  1  5  9]
 [ 3 10  5 10]
 [ 1  2  3  4]]


[ 1  2  3  4  5  7  9 10]
Zero is not in the array


In [ ]:
import numpy as np
x1=np.array([[3, 7, 5, 5],
      [10, 1, 5, 9],
      [3, 10, 5, 10],
      [1, 2, 3, 4]])
print(x1)
print("\n")
x2=x1.diagonal()
print("Largest no in the diagonal: ",max(x2))

[[ 3  7  5  5]
 [10  1  5  9]
 [ 3 10  5 10]
 [ 1  2  3  4]]


Largest no in the diagonal:  5


In [ ]:
import numpy as np
x1=np.array([[3, 7, 5, 5],
      [10, 1, 5, 9],
      [3, 10, 5, 10],
      [1, 2, 3, 4]])
print(x1)
print("\n")
x2=x1.diagonal()
x3=np.sum(x2)
print("Sum of the nos in the diagonal: ",x3)

[[ 3  7  5  5]
 [10  1  5  9]
 [ 3 10  5 10]
 [ 1  2  3  4]]


Sum of the nos in the diagonal:  13


In [ ]:
import numpy as np
x1=np.array([[3, 7, 5, 5],
      [10, 1, 5, 9],
      [3, 10, 5, 10],
      [1, 2, 3, 4]])
print(x1)
print("\n")
x2=np.unique(x1)
x3=x2.tolist()
x3.sort()
print("Sum of the largest three nos in the array: ",x3[-1]+x3[-2]+x3[-3])

[[ 3  7  5  5]
 [10  1  5  9]
 [ 3 10  5 10]
 [ 1  2  3  4]]


Sum of the largest three nos in the array:  26


In [ ]:
import numpy as np
x1=np.array([[3, 7, 5, 5],
      [10, 1, 5, 9],
      [3, 10, 5, 10],
      [1, 2, 3, 4]])
print(x1)
print("\n")
print ("The row wise mean: ")
print (np.mean(x1,axis=1))

[[ 3  7  5  5]
 [10  1  5  9]
 [ 3 10  5 10]
 [ 1  2  3  4]]


The row wise mean: 
[5.   6.25 7.   2.5 ]


In [ ]:
import numpy as np
x1=np.array([[3, 7, 5, 5],
      [10, 1, 5, 9],
      [3, 10, 5, 10],
      [1, 2, 3, 4]])
print(x1)
print("\n")
print ("The column wise mean: ")
print (np.mean(x1,axis=0))

[[ 3  7  5  5]
 [10  1  5  9]
 [ 3 10  5 10]
 [ 1  2  3  4]]


The column wise mean: 
[4.25 5.   4.5  7.  ]


In [ ]:
import numpy as np
A=np.array([[3, 7, 5],
      [10, 1, 5],
      [3, 10, 5]])
print(A)
print("\n")
B=np.array([[4, 8, 6],
      [9, 1, 6],
      [4, 9, 6]])
print(B)
print("\n")
C=np.greater(A, B)
C=np.where(C == True,1,0)
print(C)

[[ 3  7  5]
 [10  1  5]
 [ 3 10  5]]


[[4 8 6]
 [9 1 6]
 [4 9 6]]


[[0 0 0]
 [1 0 0]
 [0 1 0]]


In [ ]:
import numpy as np
A=np.array([[3, 7, 5],
      [10, 1, 5],
      [3, 10, 5]])
print(A)
print("\n")
B=np.array([[4, 8, 6],
      [9, 1, 6],
      [4, 9, 6]])
print(B)
print("\n")
C=np.greater(A, B)
C=np.where(C == True,A,B)
print(C)

[[ 3  7  5]
 [10  1  5]
 [ 3 10  5]]


[[4 8 6]
 [9 1 6]
 [4 9 6]]


[[ 4  8  6]
 [10  1  6]
 [ 4 10  6]]


In [77]:
import numpy as np
x = np.array([4, 3, 2, 13, 8, 4, 1, 10, 15, 5])
print(x)
s=np.sum(x)
n=len(x)
m=s/n
print("Mean of the array: ",m)

x1=np.subtract(x,m)
x2=np.multiply(x1,x1)
s1=np.sum(x2)
n1=len(x2)
v=s1/n1
print("Standard deviation of the array: ",np.sqrt(v))

[ 4  3  2 13  8  4  1 10 15  5]
Mean of the array:  6.5
Standard deviation of the array:  4.544227107000705


In [78]:
import numpy as np
x = np.array([4, 3, 2, 13, 8, 4, 1, 10, 15, 5])
print(x)
s=np.sum(x)
n=len(x)
m=s/n
print("Mean of the array: ",m)

x1=np.subtract(x,m)
x2=np.multiply(x1,x1)
s1=np.sum(x2)
n1=len(x2)
v=s1/n1
x3=np.sqrt(v)
print("Standard deviation of the array: ",x3)

x4=x1/x3
print("Normalise the array by performing (xi-xmean)/xstd.:",x4)

[ 4  3  2 13  8  4  1 10 15  5]
Mean of the array:  6.5
Standard deviation of the array:  4.544227107000705
Normalise the array by performing (xi-xmean)/xstd.: [-0.55014856 -0.77020798 -0.99026741  1.43038626  0.33008914 -0.55014856
 -1.21032683  0.77020798  1.8705051  -0.33008914]
